# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: nullvoidos
description: Forensic & Pentesting Lab - Immutable Environment

base-image: ghcr.io/ublue-os/vauxite
image-version: latest 

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - nano
      - wget
      - curl
      - tmux
      - git
      - htop
      - rsync
      - python3-pip
      - words
      - distrobox
      - fastfetch
      #tool pentesting
      - nmap
      - nmap-ncat
      - wireshark
      - wireshark-cli
      - python3-impacket
      - gobuster
      - samba-client
      - cifs-utils
      - sqlmap        
      - mariadb          
      - postgresql        
      - sqlite  
      - remmina          
      - freerdp          
      - openssh-clients 
      - whois
      
    remove:
      - firefox 
      - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - install:
          # --- BROWSER ---
          - com.brave.Browser
          - com.google.Chrome
          # --- TOOLS ---
          - org.keepassxc.KeePassXC
          - com.visualstudio.code
          
  - type: files
    files:
      - source: files/usr/bin/init-kali  # Il file che hai creato tu
        destination: /usr/bin/init-kali  # Dove va a finire nel sistema
        mode: 0755
        # Lo rende eseguibile
  - type: signing
