# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: nullvoidos
description: Forensic & Pentesting Lab - Immutable Environment

base-image: ghcr.io/ublue-os/aurora
image-version: latest

# --- STAGE DI PREPARAZIONE ---
# Qui prepariamo gli script in un ambiente non protetto per dare i permessi
stages:
  - name: script-prepper
    from: docker.io/library/ubuntu:22.04
    modules:
      - type: script
        snippets:
          # Creiamo la cartella di output nello stage
          - mkdir -p /out
          # Copiamo i tuoi file dalla cartella config della repo allo stage
          - cp $CONFIG_DIRECTORY/sift-create.sh /out/init-sift
          - cp $CONFIG_DIRECTORY/kali-create.sh /out/init-kali
          # Qui il chmod funziona perché non siamo su un filesystem Read-Only
          - chmod 0755 /out/init-sift
          - chmod 0755 /out/init-kali



modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - tmux
      - htop
      - rsync
      - distrobox
      - fastfetch
      - samba-client
      - cifs-utils      
      - fuse-sshfs
      - libvirt-client
      - virt-install
    #remove:

  - type: default-flatpaks
    configurations:
      - install:
          # --- BROWSER ---
          - com.brave.Browser
          - com.google.Chrome
          # --- TOOLS ---
          - org.keepassxc.KeePassXC
          - com.visualstudio.code
          
  - type: files
    files:
      - source: sift-create.sh  
        destination: /usr/bin/init-sift  
        mode: 0755

      - source: kali-create.sh  
        destination: /usr/bin/init-kali 
        mode: 0755

  # --- COPIA DEGLI SCRIPT PRONTI ---
  # Copiamo i file dallo stage 'script-prepper' a /usr/bin
  - type: copy
    from: script-prepper
    src: /out/init-sift
    dest: /usr/bin/init-sift
    
  - type: copy
    from: script-prepper
    src: /out/init-kali
    dest: /usr/bin/init-kali

  - type: signing
        
  - type: signing
