# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: nullvoidos
description: Forensic & Pentesting Lab - Immutable Environment

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest 

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      # --- PENTESTING & NETWORKING ---
      - nmap
      - wireshark
      - aircrack-ng
      - gobuster
      - socat
      - ncat
      - john
      - python3-impacket
      # --- FORENSIC & ANALYSIS ---
      - sleuthkit
      - foremost
      - binwalk
      - hashdeep
      # --- UTILS FONDAMENTALI ---
      - nano
      - wget
      - curl
      - tmux
      - git
      - htop
      - rsync
      - python3-pip
    remove:
      - firefox 
      - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - install:
          # --- BROWSER ---
          - com.brave.Browser
          - com.google.Chrome
          # --- TOOLS ---
          - org.keepassxc.KeePassXC
          - com.visualstudio.code

  - type: signing
