# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: nullvoidos
description: Forensic & Pentesting Lab - Immutable Environment

base-image: ghcr.io/ublue-os/budgie-atomic-main
image-version: latest

# --- STAGE DI PREPARAZIONE ---
# Qui prepariamo gli script in un ambiente non protetto per dare i permessi
stages:
  - name: script-prepper
    from: docker.io/library/ubuntu:22.04
    modules:
      - type: script
        snippets:
          # Creiamo la cartella di output nello stage
          - mkdir -p /out
          - mkdir -p /etc/bashrc.d
          - mkdir -p /etc/profile.d
          # Copiamo i tuoi file dalla cartella config della repo allo stage
          - cp $CONFIG_DIRECTORY/sift-create.sh /out/init-sift
          - cp $CONFIG_DIRECTORY/kali-create.sh /out/init-kali
          - cp $CONFIG_DIRECTORY/dbx-cmd /out/dbx-cmd
          - cp $CONFIG_DIRECTORY/dbx-destroy /out/dbx-destroy
          - cp $CONFIG_DIRECTORY/nvx /out/nvx
          - cp $CONFIG_DIRECTORY/nvx-where /out/nvx-where
          - cp $CONFIG_DIRECTORY/nvx-install /out/nvx-install
          - cp $CONFIG_DIRECTORY/nvx-update /out/nvx-update
          - cp $CONFIG_DIRECTORY/nvx-shield /out/nvx-shield
          - cp $CONFIG_DIRECTORY/nvx-remove /out/nvx-remove
          # Qui il chmod funziona perché non siamo su un filesystem Read-Only
          - chmod 0755 /out/init-sift
          - chmod 0755 /out/init-kali
          - chmod 0755 /out/dbx-cmd
          - chmod 0755 /out/dbx-destroy
          - chmod 0755 /out/nvx
          - chmod 0755 /out/nvx-where
          - chmod 0755 /out/nvx-install
          - chmod 0755 /out/nvx-update
          - chmod 0755 /out/nvx-shield
          - chmod 0755 /out/nvx-remove

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      # --- IL CUORE DI AURORA (Container & Terminal) ---
      - ptyxis
      # - starship
      - distrobox

      # --- RETE & VPN (Per collegarti al lab remoto) ---
      - tailscale
      - network-manager-applet
      - blueman

      # --- SWAY ESSENTIALS (Per rendere l'interfaccia usabile) ---
      - wofi
      - waybar
      - thunar
      - thunar-archive-plugin
      - file-roller
      - grim
      - slurp
      - mate-polkit
      - pavucontrol

      # --- UTILITY FORENSI & SYSTEM (Sulla base host) ---
      - rclone
      - restic
      - testdisk
      - wireshark
      - htop
      - fastfetch
      - spice-vdagent

      # --- SUPPORTO VPN (Specifico per Proving Grounds/HTB) ---
      - NetworkManager-openvpn
      - NetworkManager-openvpn-gnome
    # remove:

  - type: default-flatpaks
    configurations:
    notify: false
      - install:
          - org.keepassxc.KeePassXC
          - org.gnome.Evince
          - org.gnome.Calculator
          - org.gnome.Characters
          - com.github.tchx84.Flatseal

  - type: files
    files:
      - source: sift-create.sh
        destination: /usr/bin/init-sift
        mode: 0755

      - source: kali-create.sh
        destination: /usr/bin/init-kali
        mode: 0755

      - source: dbx-destroy
        destination: /usr/bin/dbx-destroy
        mode: 0755

      - source: nullvoid_background.png
        destination: /usr/share/backgrounds/nullvoidos/nullvoid_background.png
        mode: 0644

      - source: nullvoid_background_chatgpt.png
        destination: /usr/share/backgrounds/nullvoidos/nullvoid_background_chatgpt.png
        mode: 0644

      - source: dbx-cmd
        destination: /usr/local/bin/dbx-cmd
        mode: 0755

      - source: nvx
        destination: /usr/local/bin/nvx
        mode: 0755
        
      - source: nvx-where
        destination: /usr/local/bin/nvx-where
        mode: 0755
        
      - source: nvx-install
        destination: /usr/local/bin/nvx-install
        mode: 0755
        
      - source: nvx-update
        destination: /usr/local/bin/nvx-update
        mode: 0755

      - source: nvx-shield
        destination: /usr/local/bin/nvx-shield
        mode: 0755
        
      - source: nvx-remove
        destination: /usr/local/bin/nvx-remove
        mode: 0755


  - type: bling
    install:
      - dconf-update-service

  # --- SERVIZI DI SISTEMA ---
  - type: systemd
    system:
      enabled:
        - podman.socket
        # - tailscaled

  # --- COPIA DEGLI SCRIPT PRONTI ---
  # Copiamo i file dallo stage 'script-prepper' a /usr/bin
  - type: copy
    from: script-prepper
    src: /out/init-sift
    dest: /usr/bin/init-sift

  - type: copy
    from: script-prepper
    src: /out/init-kali
    dest: /usr/bin/init-kali

  - type: copy
    from: script-prepper
    src: /out/dbx-destroy
    dest: /usr/bin/dbx-destroy

  - type: copy
    from: script-prepper
    src: /out/dbx-cmd
    dest: /usr/local/bin/dbx-cmd

  - type: copy
    from: script-prepper
    src: /out/nvx
    dest: /usr/local/bin/nvx
    
  - type: copy
    from: script-prepper
    src: /out/nvx-where
    dest: /usr/local/bin/nvx-where
    
  - type: copy
    from: script-prepper
    src: /out/nvx-install
    dest: /usr/local/bin/nvx-install
    
  - type: copy
    from: script-prepper
    src: /out/nvx-update
    dest: /usr/local/bin/nvx-update

  - type: copy
    from: script-prepper
    src: /out/nvx-shield
    dest: /usr/local/bin/nvx-shield
    
  - type: copy
    from: script-prepper
    src: /out/nvx-remove
    dest: /usr/local/bin/nvx-remove

  - type: signing
