# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: nullvoidos
description: Forensic & Pentesting Lab - Immutable Environment

base-image: ghcr.io/ublue-os/budgie-atomic-main
image-version: latest

# --- STAGE DI PREPARAZIONE ---
# Qui prepariamo gli script in un ambiente non protetto per dare i permessi
stages:
  - name: script-prepper
    from: docker.io/library/ubuntu:22.04
    modules:
      - type: script
        snippets:
          # Creiamo la cartella di output nello stage
          - mkdir -p /out
          # Copiamo i tuoi file dalla cartella config della repo allo stage
          - cp $CONFIG_DIRECTORY/sift-create.sh /out/init-sift
          - cp $CONFIG_DIRECTORY/kali-create.sh /out/init-kali
          # Qui il chmod funziona perché non siamo su un filesystem Read-Only
          - chmod 0755 /out/init-sift
          - chmod 0755 /out/init-kali



modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      # --- IL CUORE DI AURORA (Container & Terminal) ---
      - ptyxis             # Il terminale perfetto per Distrobox
      #- starship           # Prompt intelligente (ti dice se sei in un container)
      - distrobox          # Gestore container (dovrebbe esserci, ma per sicurezza)
      
      # --- RETE & VPN (Per collegarti al lab remoto) ---
      - tailscale          # VPN Mesh
      - network-manager-applet # Icona WiFi nella barra (FONDAMENTALE su Sway)
      - blueman            # Gestore Bluetooth

      # --- SWAY ESSENTIALS (Per rendere l'interfaccia usabile) ---
      - wofi               # Menu avvio app (simile a Spotlight/Krunner)
      - waybar             # La barra in alto (ora, batteria, workspace)
      - thunar             # File Manager leggero (alternativa a Dolphin)
      - thunar-archive-plugin # Per aprire zip/tar.gz con tasto destro
      - file-roller        # Gestore archivi
      - grim               # Screenshot tool (backend)
      - slurp              # Selezione area screenshot
      - mate-polkit       # POPUP PASSWORD (essenziale per GUI sudo)
      - pavucontrol        # Controllo volume audio avanzato

      # --- UTILITY FORENSI & SYSTEM (Sulla base host) ---
      - rclone             # Per montare cloud storage (Google Drive, S3)
      - restic             # Per backup criptati
      - testdisk           # Recupero partizioni (meglio averlo sull'host)
      - wireshark          # Analisi pacchetti (GUI)
      - htop               # Monitor risorse
      - fastfetch          # Per vedere le info sistema (stile neofetch)

      # --- SUPPORTO VPN (Specifico per Proving Grounds/HTB) ---
      - NetworkManager-openvpn # <--- FONDAMENTALE per importare i file .ovpn
      - NetworkManager-openvpn-gnome # Plugin grafico per l'applet
    #remove:

  - type: default-flatpaks
    configurations:
      - install:
          # --- BROWSER ---
          - com.brave.Browser
          - com.google.Chrome
          # --- TOOLS ---
          - org.keepassxc.KeePassXC
          - com.visualstudio.code
          
  - type: files
    files:
      - source: sift-create.sh  
        destination: /usr/bin/init-sift  
        mode: 0755

      - source: kali-create.sh  
        destination: /usr/bin/init-kali 
        mode: 0755

  # --- SERVIZI DI SISTEMA ---
  - type: systemd
    system:
      enabled:
        - podman.socket    # Tienilo, serve a Distrobox per funzionare bene
        # - tailscaled     <--- RIMOSSO (lo lasciamo spento)
  
  # --- COPIA DEGLI SCRIPT PRONTI ---
  # Copiamo i file dallo stage 'script-prepper' a /usr/bin
  - type: copy
    from: script-prepper
    src: /out/init-sift
    dest: /usr/bin/init-sift
    
  - type: copy
    from: script-prepper
    src: /out/init-kali
    dest: /usr/bin/init-kali

  - type: signing
        
  - type: signing
