# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: nullvoidos
description: Forensic & Pentesting Lab - Immutable Environment

base-image: ghcr.io/ublue-os/budgie-atomic-main
image-version: latest

modules:
  # --- (OPZIONALE) Copia contenuto della cartella system/ nella root dell'immagine ---
  # ATTENZIONE: se in system/ hai system/usr/local/* puoi rompere la build.
  # Se ti ha già dato errori, commenta questo blocco.
  - type: files
    files:
      - source: system
        destination: /

  # --- Pacchetti host via rpm-ostree ---
  - type: rpm-ostree
    install:
      # Container & Terminal
      - ptyxis
      - distrobox

      # Rete & VPN
      - tailscale
      - network-manager-applet
      - blueman

      # Budgie/Sway essentials (come li avevi)
      - wofi
      - waybar
      - thunar
      - thunar-archive-plugin
      - file-roller
      - grim
      - slurp
      - mate-polkit
      - pavucontrol

      # Utility forensi / system
      - rclone
      - restic
      - testdisk
      - wireshark
      - htop
      - fastfetch
      - spice-vdagent

      # OpenVPN support
      - NetworkManager-openvpn
      - NetworkManager-openvpn-gnome

  # --- Flatpaks di default ---
  - type: default-flatpaks
    configurations:
      - install:
          - com.brave.Browser
          - com.google.Chrome
          - org.keepassxc.KeePassXC
          - com.visualstudio.code

  # --- Crea directory target (il modulo files NON fa mkdir -p) ---
  - type: script
    snippets:
      - |
        mkdir -p /usr/share/backgrounds/nullvoidos
        mkdir -p /etc/bashrc.d
        mkdir -p /etc/profile.d
     
        # Forza permessi di esecuzione (robusto anche se "mode" non viene rispettato)
        chmod 0755 /usr/bin/init-sift /usr/bin/init-kali /usr/bin/dbx-cmd || true

        # Se SELinux è presente, prova a sistemare i context (non fallire se manca restorecon)
        command -v restorecon >/dev/null 2>&1 && restorecon -v /usr/bin/init-sift /usr/bin/init-kali /usr/bin/dbx-cmd || true


  # --- Copia file nell'immagine (dalla repo) ---
  - type: files
    files:
      # Init scripts per creare i container (rootful)
      - source: sift-create.sh
        destination: /usr/bin/init-sift
        mode: 0755

      - source: kali-create.sh
        destination: /usr/bin/init-kali
        mode: 0755

      # Wallpaper
      - source: nullvoid_background.png
        destination: /usr/share/backgrounds/nullvoidos/nullvoid_background.png
        mode: 0644

      - source: nullvoid_background_chatgpt.png
        destination: /usr/share/backgrounds/nullvoidos/nullvoid_background_chatgpt.png
        mode: 0644

      # DBX wrapper + shell functions/hook
      # Metto dbx-cmd in /usr/bin per evitare conflitti con /usr/local sulle basi uBlue
      - source: dbx-cmd
        destination: /usr/bin/dbx-cmd
        mode: 0755

      - source: dbx.sh
        destination: /etc/bashrc.d/dbx.sh
        mode: 0644

      - source: dbx.sh
        destination: /etc/profile.d/dbx.sh
        mode: 0644

  # --- Bling / servizi ---
  - type: bling
    install:
      - dconf-update-service

  - type: systemd
    system:
      enabled:
        - podman.socket

  

  - type: signing
