# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: nullvoidos
description: Forensic & Pentesting Lab - Immutable Environment

base-image: ghcr.io/ublue-os/budgie-atomic-main
image-version: latest

# --- STAGE DI PREPARAZIONE ---
# Qui prepariamo gli script in un ambiente non protetto per dare i permessi
stages:
  - name: script-prepper
    from: docker.io/library/ubuntu:22.04
    modules:
      - type: script
        snippets:
          # Creiamo la cartella di output nello stage
          - mkdir -p /out
          - mkdir -p /etc/bashrc.d
          - mkdir -p /etc/profile.d
          # Copiamo i tuoi file dalla cartella config della repo allo stage
          - cp $CONFIG_DIRECTORY/sift-create.sh /out/init-sift
          - cp $CONFIG_DIRECTORY/kali-create.sh /out/init-kali
          - cp $CONFIG_DIRECTORY/dbx-cmd /out/dbx-cmd
          # Qui il chmod funziona perché non siamo su un filesystem Read-Only
          - chmod 0755 /out/init-sift
          - chmod 0755 /out/init-kali
          - chmod 0755 /out/dbx-cmd

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      # --- IL CUORE DI AURORA (Container & Terminal) ---
      - ptyxis
      # - starship
      - distrobox

      # --- RETE & VPN (Per collegarti al lab remoto) ---
      - tailscale
      - network-manager-applet
      - blueman

      # --- SWAY ESSENTIALS (Per rendere l'interfaccia usabile) ---
      - wofi
      - waybar
      - thunar
      - thunar-archive-plugin
      - file-roller
      - grim
      - slurp
      - mate-polkit
      - pavucontrol

      # --- UTILITY FORENSI & SYSTEM (Sulla base host) ---
      - rclone
      - restic
      - testdisk
      - wireshark
      - htop
      - fastfetch
      - spice-vdagent

      # --- SUPPORTO VPN (Specifico per Proving Grounds/HTB) ---
      - NetworkManager-openvpn
      - NetworkManager-openvpn-gnome
    # remove:

  - type: default-flatpaks
    configurations:
      - install:
          # --- BROWSER ---
          - com.brave.Browser
          - com.google.Chrome
          # --- TOOLS ---
          - org.keepassxc.KeePassXC
          - com.visualstudio.code

  - type: files
    files:
      - source: sift-create.sh
        destination: /usr/bin/init-sift
        mode: 0755

      - source: kali-create.sh
        destination: /usr/bin/init-kali
        mode: 0755

      - source: nullvoid_background.png
        destination: /usr/share/backgrounds/nullvoidos/nullvoid_background.png
        mode: 0644

      - source: nullvoid_background_chatgpt.png
        destination: /usr/share/backgrounds/nullvoidos/nullvoid_background_chatgpt.png
        mode: 0644

      - source: dbx-cmd
        destination: /usr/local/bin/dbx-cmd
        mode: 0755

      - source: dbx.sh
        destination: /etc/bashrc.d/dbx.sh
        mode: 0644

      - source: dbx.sh
        destination: /etc/profile.d/dbx.sh
        mode: 0644

  - type: bling
    install:
      - dconf-update-service

  # --- SERVIZI DI SISTEMA ---
  - type: systemd
    system:
      enabled:
        - podman.socket
        # - tailscaled

  # --- COPIA DEGLI SCRIPT PRONTI ---
  # Copiamo i file dallo stage 'script-prepper' a /usr/bin
  - type: copy
    from: script-prepper
    src: /out/init-sift
    dest: /usr/bin/init-sift

  - type: copy
    from: script-prepper
    src: /out/init-kali
    dest: /usr/bin/init-kali

  - type: copy
    from: script-prepper
    src: /out/dbx-cmd
    dest: /usr/local/bin/dbx-cmd

  - type: signing
