# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: nullvoidos
description: Forensic & Pentesting Lab - Immutable Environment

base-image: ghcr.io/ublue-os/aurora
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - tmux
      - htop
      - rsync
      - distrobox
      - fastfetch
      - samba-client
      - cifs-utils      
      - fuse-sshfs
      - libvirt-client
      - virt-install
    #remove:

  - type: default-flatpaks
    configurations:
      - install:
          # --- BROWSER ---
          - com.brave.Browser
          - com.google.Chrome
          # --- TOOLS ---
          - org.keepassxc.KeePassXC
          - com.visualstudio.code
          
  - type: files
    files:
      - source: sift-create.sh  
        destination: /usr/bin/init-sift  
        mode: 0755

      - source: kali-create.sh  
        destination: /usr/bin/init-kali 
        mode: 0755
        
  - type: signing
