name: Build ISO

on:
  workflow_dispatch: # Questo permette di avviarlo manualmente con un click

jobs:
  bluebuild-iso:
    name: Build ISO Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          # Assicurati che questo nome corrisponda al tuo file ricetta!
          - recipe.yml
    steps:
      - name: Build ISO Image
        uses: blue-build/github-action@v1.10
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          # QUESTA è la riga magica che dice di fare l'ISO invece del container normale
          iso_only: true
