//! C code generation for Nullang (SPEC §7). Lowers the checked AST to
//! portable C. `World` parameters and arguments are **erased** — a
//! compile-time capability token (SPEC §5), invisible at runtime. Enums
//! lower to `long`; a `.symbol` becomes its declaration index.
//!
//! Control-flow expressions (`if`, `match`) are lowered out of expression
//! position into statements plus a fresh temporary, so they compose anywhere
//! a value is expected. `lower` returns a C expression string and emits any
//! needed prelude statements into `out`; it returns "" for a Unit result
//! (the statements have already been emitted).
use std::collections::HashMap;

use crate::ast::*;
use crate::check::{Checked, EnumInfo, SigTable};

/// The C struct name for a tagged (payload-carrying) enum.
fn enum_struct_name(id: u32) -> String {
    format!("nlenum{}", id)
}

const PRELUDE: &str = "\
/* generated by nullang v0.1 — do not edit */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void nullang_print(const char* s) { fputs(s, stdout); fputs(\"\\n\", stdout); }

/* Explicit string composition (SPEC §10). Allocations are not freed: v0.2
   programs are short-lived and arena/ownership is a §11 deferral. */
static const char* nullang_concat(const char* a, const char* b) {
  size_t la = strlen(a), lb = strlen(b);
  char* r = malloc(la + lb + 1);
  memcpy(r, a, la);
  memcpy(r + la, b, lb + 1); /* trailing NUL from b */
  return r;
}

static const char* nullang_str_of_int(long n) {
  char* r = malloc(24); /* 64-bit signed: 20 digits + sign + NUL */
  snprintf(r, 24, \"%ld\", n);
  return r;
}

/* Tier 0 string decomposition. */
static long nullang_str_len(const char* s) { return (long)strlen(s); }

/* substr(s, start, len): indices clamp to bounds so it is total. */
static const char* nullang_substr(const char* s, long start, long len) {
  long n = (long)strlen(s);
  if (start < 0) start = 0;
  if (start > n) start = n;
  if (len < 0) len = 0;
  long avail = n - start;
  if (len > avail) len = avail;
  char* r = malloc((size_t)len + 1);
  memcpy(r, s + start, (size_t)len);
  r[len] = '\\0';
  return r;
}

/* Tier 0 file I/O. World is erased at codegen, so it is not a C parameter;
   the capability lives in the fn's `uses` clause (checked) and the grant in
   system.null (enforced by Landlock at run time). Errors are swallowed into
   an empty string / no-op for now — a Result-returning variant (SPEC §10) is
   the follow-up. Allocations are not freed (short-lived programs, §11). */
static const char* nullang_read_file(const char* path) {
  FILE* f = fopen(path, \"rb\");
  if (!f) return \"\";
  if (fseek(f, 0, SEEK_END) != 0) { fclose(f); return \"\"; }
  long sz = ftell(f);
  if (sz < 0) { fclose(f); return \"\"; }
  rewind(f);
  char* buf = malloc((size_t)sz + 1);
  size_t got = fread(buf, 1, (size_t)sz, f);
  buf[got] = '\\0';
  fclose(f);
  return buf;
}

static void nullang_write_file(const char* path, const char* content) {
  FILE* f = fopen(path, \"wb\");
  if (!f) return;
  fputs(content, f);
  fclose(f);
}
";

pub fn emit(file: &File, checked: &Checked) -> String {
    let mut out = String::from(PRELUDE);
    out.push('\n');
    let cg = Codegen {
        sigs: &checked.sigs,
        symbols: &checked.symbols,
        enums: &checked.enums,
    };

    // Tagged enums lower to a `{ tag, union }` struct (SPEC §7); emit their
    // typedefs before any function references them. Payload-free enums stay
    // bare `long` and need no typedef.
    for (id, e) in checked.enums.iter().enumerate() {
        if e.tagged {
            cg.emit_enum_typedef(&mut out, id as u32, e);
        }
    }

    for item in &file.items {
        if let Item::Func(f) = item {
            if f.name != "main" {
                cg.emit_func(&mut out, f);
            }
        }
    }
    for item in &file.items {
        if let Item::Func(f) = item {
            if f.name == "main" {
                cg.emit_main(&mut out, f);
            }
        }
    }
    out
}

struct Codegen<'a> {
    sigs: &'a SigTable,
    symbols: &'a HashMap<String, (u32, usize)>,
    enums: &'a [EnumInfo],
}

impl<'a> Codegen<'a> {
    /// If `ty` is a tagged enum, its struct id; otherwise `None`.
    fn tagged_id(&self, ty: Ty) -> Option<u32> {
        match ty {
            Ty::Enum(id) if self.enums.get(id as usize).map_or(false, |e| e.tagged) => Some(id),
            _ => None,
        }
    }

    /// The C type for a Nullang type: a struct name for tagged enums, the
    /// scalar lowering otherwise (SPEC §7).
    fn c_type_of(&self, ty: Ty) -> String {
        match self.tagged_id(ty) {
            Some(id) => enum_struct_name(id),
            None => ty.c_type().to_string(),
        }
    }

    /// A zero-initialiser for a fresh temporary of this type. Tagged enums
    /// are structs and need `{0}`; scalars accept it too but read clearer as `0`.
    fn zero_of(&self, ty: Ty) -> &'static str {
        if self.tagged_id(ty).is_some() {
            "{0}"
        } else {
            "0"
        }
    }

    fn emit_enum_typedef(&self, out: &mut String, id: u32, e: &EnumInfo) {
        out.push_str("typedef struct {\n  long tag;\n  union {\n");
        for (idx, v) in e.variants.iter().enumerate() {
            if let Some(pty) = v.payload {
                out.push_str(&format!("    {} _v{};\n", pty.c_type(), idx));
            }
        }
        out.push_str(&format!("  }} u;\n}} {};\n\n", enum_struct_name(id)));
    }

    fn emit_func(&self, out: &mut String, f: &Func) {
        let ret = self.sigs.get(&f.name).map(|s| s.ret).unwrap_or(Ty::Unit);
        let mut locals: HashMap<String, Ty> = HashMap::new();
        let mut params = Vec::new();
        for (i, p) in f.params.iter().enumerate() {
            let ty = self
                .sigs
                .get(&f.name)
                .and_then(|s| s.params.get(i).copied())
                .unwrap_or(Ty::Int);
            locals.insert(p.name.clone(), ty);
            if ty != Ty::World {
                params.push(format!("{} {}", self.c_type_of(ty), p.name));
            }
        }
        let param_list = if params.is_empty() {
            "void".to_string()
        } else {
            params.join(", ")
        };
        out.push_str(&format!("{} {}({}) {{\n", self.c_type_of(ret), f.name, param_list));

        let mut fresh = 0usize;
        let tail = self.lower_block(&f.body, &locals, out, &mut fresh);
        match tail {
            Some(v) if ret != Ty::Unit && !v.is_empty() => {
                out.push_str(&format!("  return {};\n", v))
            }
            Some(v) if !v.is_empty() => out.push_str(&format!("  {};\n", v)),
            _ => {}
        }
        out.push_str("}\n\n");
    }

    fn emit_main(&self, out: &mut String, f: &Func) {
        let mut locals: HashMap<String, Ty> = HashMap::new();
        for p in &f.params {
            locals.insert(p.name.clone(), p.ty.resolved.unwrap_or(Ty::World));
        }
        out.push_str("int main(void) {\n");
        let mut fresh = 0usize;
        let tail = self.lower_block(&f.body, &locals, out, &mut fresh);
        match tail {
            Some(v) if !v.is_empty() => out.push_str(&format!("  return {};\n", v)),
            _ => out.push_str("  return 0;\n"),
        }
        out.push_str("}\n\n");
    }

    /// Emit a block's statements (child scope) and return its trailing value.
    fn lower_block(
        &self,
        block: &Block,
        outer: &HashMap<String, Ty>,
        out: &mut String,
        fresh: &mut usize,
    ) -> Option<String> {
        let mut locals = outer.clone();
        for stmt in &block.stmts {
            self.lower_stmt(stmt, &mut locals, out, fresh);
        }
        block.tail.as_ref().map(|e| self.lower(e, &locals, out, fresh))
    }

    /// Emit a block, assigning its trailing value to `target`.
    fn lower_block_into(
        &self,
        block: &Block,
        target: &str,
        outer: &HashMap<String, Ty>,
        out: &mut String,
        fresh: &mut usize,
    ) {
        let mut locals = outer.clone();
        for stmt in &block.stmts {
            self.lower_stmt(stmt, &mut locals, out, fresh);
        }
        if let Some(e) = &block.tail {
            let v = self.lower(e, &locals, out, fresh);
            if !v.is_empty() {
                out.push_str(&format!("  {} = {};\n", target, v));
            }
        }
    }

    /// Emit a block whose trailing value (if any) is used only for effect.
    fn lower_block_stmt(
        &self,
        block: &Block,
        outer: &HashMap<String, Ty>,
        out: &mut String,
        fresh: &mut usize,
    ) {
        let mut locals = outer.clone();
        for stmt in &block.stmts {
            self.lower_stmt(stmt, &mut locals, out, fresh);
        }
        if let Some(e) = &block.tail {
            let v = self.lower(e, &locals, out, fresh);
            if !v.is_empty() {
                out.push_str(&format!("  {};\n", v));
            }
        }
    }

    fn lower_stmt(
        &self,
        stmt: &Stmt,
        locals: &mut HashMap<String, Ty>,
        out: &mut String,
        fresh: &mut usize,
    ) {
        match stmt {
            Stmt::Let { name, value, .. } => {
                let ty = self.ty_of(value, locals);
                let v = self.lower(value, locals, out, fresh);
                if !v.is_empty() {
                    out.push_str(&format!("  {} {} = {};\n", self.c_type_of(ty), name, v));
                }
                locals.insert(name.clone(), ty);
            }
            Stmt::Expr(e) => {
                let v = self.lower(e, locals, out, fresh);
                if !v.is_empty() {
                    out.push_str(&format!("  {};\n", v));
                }
            }
            Stmt::Return { value, .. } => match value {
                Some(e) => {
                    let v = self.lower(e, locals, out, fresh);
                    out.push_str(&format!("  return {};\n", v));
                }
                None => out.push_str("  return;\n"),
            },
        }
    }

    fn lower(
        &self,
        e: &Expr,
        locals: &HashMap<String, Ty>,
        out: &mut String,
        fresh: &mut usize,
    ) -> String {
        match e {
            Expr::Str { value, .. } => c_string_literal(value),
            Expr::Int { value, .. } => format!("{}", value),
            Expr::Bool { value, .. } => (if *value { "1" } else { "0" }).to_string(),
            Expr::Ident { name, .. } => name.clone(),
            Expr::Symbol { name, arg, .. } => {
                let (id, idx) = self.symbols.get(name).copied().unwrap_or((0, 0));
                // A payload-free enum is a bare index; a tagged enum (even a
                // bare variant of one) is a `{ tag, union }` compound literal.
                if self.tagged_id(Ty::Enum(id)).is_some() {
                    let sname = enum_struct_name(id);
                    match arg {
                        Some(e) => {
                            let v = self.lower(e, locals, out, fresh);
                            format!("(({}){{ .tag = {}, .u._v{} = {} }})", sname, idx, idx, v)
                        }
                        None => format!("(({}){{ .tag = {} }})", sname, idx),
                    }
                } else {
                    format!("{}", idx)
                }
            }
            Expr::Unary { operand, .. } => format!("(-{})", self.lower(operand, locals, out, fresh)),
            Expr::Binary { op, lhs, rhs, .. } => {
                let l = self.lower(lhs, locals, out, fresh);
                let r = self.lower(rhs, locals, out, fresh);
                // String equality compares contents, not pointers: lower to
                // `strcmp(l, r) == 0` / `!= 0`. The checker guarantees both
                // sides are String here.
                if op.is_equality() && self.ty_of(lhs, locals) == Ty::String {
                    format!("(strcmp({}, {}) {} 0)", l, r, op.c_op())
                } else {
                    format!("({} {} {})", l, op.c_op(), r)
                }
            }
            Expr::Call { callee, args, .. } => {
                let sig = self.sigs.get(callee);
                let c_name = sig.map(|s| s.c_name.clone()).unwrap_or_else(|| callee.clone());
                let mut emitted = Vec::new();
                for (i, arg) in args.iter().enumerate() {
                    let is_world = sig
                        .and_then(|s| s.params.get(i))
                        .map_or(false, |p| *p == Ty::World);
                    if !is_world {
                        emitted.push(self.lower(arg, locals, out, fresh));
                    }
                }
                format!("{}({})", c_name, emitted.join(", "))
            }
            Expr::If { cond, then_blk, else_blk, .. } => {
                let ty = self.ty_of(e, locals);
                let c = self.lower(cond, locals, out, fresh);
                if ty == Ty::Unit {
                    out.push_str(&format!("  if ({}) {{\n", c));
                    self.lower_block_stmt(then_blk, locals, out, fresh);
                    out.push_str("  } else {\n");
                    self.lower_block_stmt(else_blk, locals, out, fresh);
                    out.push_str("  }\n");
                    String::new()
                } else {
                    let tmp = self.fresh_var(fresh);
                    out.push_str(&format!("  {} {} = {};\n", self.c_type_of(ty), tmp, self.zero_of(ty)));
                    out.push_str(&format!("  if ({}) {{\n", c));
                    self.lower_block_into(then_blk, &tmp, locals, out, fresh);
                    out.push_str("  } else {\n");
                    self.lower_block_into(else_blk, &tmp, locals, out, fresh);
                    out.push_str("  }\n");
                    tmp
                }
            }
            Expr::Match { scrutinee, arms, .. } => {
                let ty = self.ty_of(e, locals);
                let scrut_ty = self.ty_of(scrutinee, locals);
                let scrut = self.lower(scrutinee, locals, out, fresh);
                let tmp = if ty == Ty::Unit {
                    None
                } else {
                    let t = self.fresh_var(fresh);
                    out.push_str(&format!("  {} {} = {};\n", self.c_type_of(ty), t, self.zero_of(ty)));
                    Some(t)
                };
                // A tagged enum is matched on its `.tag`; bind the scrutinee to
                // a temporary so payloads can be read out. A payload-free enum
                // switches on its bare value directly.
                let (switch_on, scrut_var) = match self.tagged_id(scrut_ty) {
                    Some(id) => {
                        let sv = self.fresh_var(fresh);
                        out.push_str(&format!("  {} {} = {};\n", enum_struct_name(id), sv, scrut));
                        (format!("{}.tag", sv), Some(sv))
                    }
                    None => (scrut, None),
                };
                out.push_str(&format!("  switch ({}) {{\n", switch_on));
                for arm in arms {
                    let (id, idx) = self.symbols.get(&arm.symbol).copied().unwrap_or((0, 0));
                    out.push_str(&format!("  case {}: {{\n", idx));
                    let mut arm_locals = locals.clone();
                    // Bind the payload into the arm scope, unless discarded (`_`).
                    if let (Some(sv), Some(binder)) = (&scrut_var, &arm.binder) {
                        if binder != "_" {
                            if let Some(pty) = self.enums[id as usize].variants[idx].payload {
                                out.push_str(&format!(
                                    "  {} {} = {}.u._v{};\n",
                                    self.c_type_of(pty),
                                    binder,
                                    sv,
                                    idx
                                ));
                                arm_locals.insert(binder.clone(), pty);
                            }
                        }
                    }
                    let v = self.lower(&arm.body, &arm_locals, out, fresh);
                    match &tmp {
                        Some(t) if !v.is_empty() => out.push_str(&format!("  {} = {};\n", t, v)),
                        _ if !v.is_empty() => out.push_str(&format!("  {};\n", v)),
                        _ => {}
                    }
                    out.push_str("  break;\n  }\n");
                }
                out.push_str("  default: break;\n  }\n");
                tmp.unwrap_or_default()
            }
        }
    }

    fn fresh_var(&self, fresh: &mut usize) -> String {
        let v = format!("_t{}", *fresh);
        *fresh += 1;
        v
    }

    /// Best-effort C type of an expression (the checker proved soundness).
    fn ty_of(&self, e: &Expr, locals: &HashMap<String, Ty>) -> Ty {
        match e {
            Expr::Str { .. } => Ty::String,
            Expr::Int { .. } => Ty::Int,
            Expr::Bool { .. } => Ty::Bool,
            Expr::Symbol { name, .. } => self
                .symbols
                .get(name)
                .map(|(id, _)| Ty::Enum(*id))
                .unwrap_or(Ty::Int),
            Expr::Ident { name, .. } => locals.get(name).copied().unwrap_or(Ty::Int),
            Expr::Unary { .. } => Ty::Int,
            Expr::Binary { op, .. } => {
                if op.is_arithmetic() {
                    Ty::Int
                } else {
                    Ty::Bool
                }
            }
            Expr::Call { callee, .. } => self.sigs.get(callee).map(|s| s.ret).unwrap_or(Ty::Unit),
            Expr::If { then_blk, .. } => match &then_blk.tail {
                Some(t) => self.ty_of(t, locals),
                None => Ty::Unit,
            },
            Expr::Match { arms, .. } => match arms.first() {
                Some(a) => {
                    // The result type is the arm body's type; bind the first
                    // arm's payload so a body that returns it types correctly.
                    let mut l = locals.clone();
                    if let Some(b) = &a.binder {
                        if b != "_" {
                            if let Some((id, idx)) = self.symbols.get(&a.symbol).copied() {
                                if let Some(pty) = self.enums[id as usize].variants[idx].payload {
                                    l.insert(b.clone(), pty);
                                }
                            }
                        }
                    }
                    self.ty_of(&a.body, &l)
                }
                None => Ty::Unit,
            },
        }
    }
}

/// Re-escape a decoded string into a C string literal.
fn c_string_literal(s: &str) -> String {
    let mut out = String::from("\"");
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
