//! C code generation for Nullang (SPEC §7). Lowers the checked AST to
//! portable C. `World` parameters and arguments are **erased** — a
//! compile-time capability token (SPEC §5), invisible at runtime. Enums
//! lower to `long`; a `.symbol` becomes its declaration index.
//!
//! Control-flow expressions (`if`, `match`) are lowered out of expression
//! position into statements plus a fresh temporary, so they compose anywhere
//! a value is expected. `lower` returns a C expression string and emits any
//! needed prelude statements into `out`; it returns "" for a Unit result
//! (the statements have already been emitted).
use std::collections::HashMap;

use crate::ast::*;
use crate::check::{Checked, EnumInfo, SigTable, StructInfo};

/// The C struct name for a tagged (payload-carrying) enum.
fn enum_struct_name(id: u32) -> String {
    format!("nlenum{}", id)
}

/// The C handle typedef name for a user struct (a pointer; SPEC §11, v0.4).
fn struct_type_name(id: u32) -> String {
    format!("nlstruct{}", id)
}

/// Mangle a struct field name for C, dodging C keywords (`int`, `default`, …)
/// the same way `mangle` does for value identifiers. Distinct prefix so it
/// never collides with `nlu_`/`nl_*`/`nlenum*`/`nlstruct*`.
fn mangle_field(name: &str) -> String {
    format!("nlf_{}", name)
}

const PRELUDE: &str = "\
/* generated by nullang v0.1 — do not edit */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

/* List<T> runtime (SPEC §11). A list value is a HANDLE — a pointer to a heap
   header — so push/set mutate through it without changing the handle, giving
   reference semantics. Elements are stored in a uniform 64-bit slot: Int/Bool
   directly, String as its pointer via intptr_t (the VM is LP64). Reads past
   the end return 0 and writes are no-ops, so indexing is total (like substr).
   Allocations are not freed (short-lived programs, §11 arena deferral). */
typedef struct { long len; long cap; long* data; } nl_list_s;
typedef nl_list_s* nl_list;
static nl_list nl_list_new(void) {
  nl_list l = malloc(sizeof(nl_list_s));
  l->len = 0; l->cap = 0; l->data = 0;
  return l;
}
static void nl_list_push(nl_list l, long v) {
  if (l->len == l->cap) {
    long nc = l->cap ? l->cap * 2 : 4;
    l->data = realloc(l->data, (size_t)nc * sizeof(long));
    l->cap = nc;
  }
  l->data[l->len++] = v;
}
static long nl_list_get(nl_list l, long i) {
  return (i >= 0 && i < l->len) ? l->data[i] : 0;
}
static void nl_list_set(nl_list l, long i, long v) {
  if (i >= 0 && i < l->len) l->data[i] = v;
}
static long nl_list_len(nl_list l) { return l->len; }

static void nullang_print(const char* s) { fputs(s, stdout); fputs(\"\\n\", stdout); }

/* Explicit string composition (SPEC §10). Allocations are not freed: v0.2
   programs are short-lived and arena/ownership is a §11 deferral. */
static const char* nullang_concat(const char* a, const char* b) {
  size_t la = strlen(a), lb = strlen(b);
  char* r = malloc(la + lb + 1);
  memcpy(r, a, la);
  memcpy(r + la, b, lb + 1); /* trailing NUL from b */
  return r;
}

static const char* nullang_str_of_int(long n) {
  char* r = malloc(24); /* 64-bit signed: 20 digits + sign + NUL */
  snprintf(r, 24, \"%ld\", n);
  return r;
}

/* Tier 0 string decomposition. */
static long nullang_str_len(const char* s) { return (long)strlen(s); }

/* substr(s, start, len): indices clamp to bounds so it is total. */
static const char* nullang_substr(const char* s, long start, long len) {
  long n = (long)strlen(s);
  if (start < 0) start = 0;
  if (start > n) start = n;
  if (len < 0) len = 0;
  long avail = n - start;
  if (len > avail) len = avail;
  char* r = malloc((size_t)len + 1);
  memcpy(r, s + start, (size_t)len);
  r[len] = '\\0';
  return r;
}

/* char_at(s, i): O(i) single-byte read — walks s only up to index i (not a
   full strlen the way substr does), stops at NUL, returns \"\" past end or for
   negative i. A left-to-right scan is O(n) instead of substr's O(n^2).
   Authored by the in-VM agent (first self-served builtin); merged host-side. */
static const char* nullang_char_at(const char* s, long i) {
  if (i < 0) return \"\";
  for (long k = 0; k < i; k++) {
    if (s[k] == '\\0') return \"\";
  }
  if (s[i] == '\\0') return \"\";
  char* r = malloc(2);
  r[0] = s[i];
  r[1] = '\\0';
  return r;
}

/* Tier 0 file I/O. World is erased at codegen, so it is not a C parameter;
   the capability lives in the fn's `uses` clause (checked) and the grant in
   system.null (enforced by Landlock at run time). Errors are swallowed into
   an empty string / no-op for now — a Result-returning variant (SPEC §10) is
   the follow-up. Allocations are not freed (short-lived programs, §11). */
static const char* nullang_read_file(const char* path) {
  FILE* f = fopen(path, \"rb\");
  if (!f) return \"\";
  if (fseek(f, 0, SEEK_END) != 0) { fclose(f); return \"\"; }
  long sz = ftell(f);
  if (sz < 0) { fclose(f); return \"\"; }
  rewind(f);
  char* buf = malloc((size_t)sz + 1);
  size_t got = fread(buf, 1, (size_t)sz, f);
  buf[got] = '\\0';
  fclose(f);
  return buf;
}

static void nullang_write_file(const char* path, const char* content) {
  FILE* f = fopen(path, \"wb\");
  if (!f) return;
  fputs(content, f);
  fclose(f);
}

/* Process arguments (Wave 2). `main` stashes argc/argv here at entry; the
   builtins read them. Pure from Nullang's view (startup data, no World). */
static int nl_argc = 0;
static char** nl_argv = 0;
static long nullang_argc(void) { return (long)nl_argc; }
static const char* nullang_argv(long i) {
  return (i >= 0 && i < (long)nl_argc) ? nl_argv[i] : \"\";
}
";

pub fn emit(file: &File, checked: &Checked) -> String {
    let mut out = String::from(PRELUDE);
    out.push('\n');
    let cg = Codegen {
        sigs: &checked.sigs,
        symbols: &checked.symbols,
        enums: &checked.enums,
        structs: &checked.structs,
    };

    // Tagged enums lower to a `{ tag, union }` struct (SPEC §7); emit their
    // typedefs before any function references them. Payload-free enums stay
    // bare `long` and need no typedef.
    for (id, e) in checked.enums.iter().enumerate() {
        if e.tagged {
            cg.emit_enum_typedef(&mut out, id as u32, e);
        }
    }

    // Structs lower to heap handles (SPEC §11, v0.4). Forward-declare every
    // handle typedef first so field types may reference any struct (including
    // self- and mutual references through the pointer), then emit the bodies.
    for (id, _) in checked.structs.iter().enumerate() {
        let n = struct_type_name(id as u32);
        out.push_str(&format!("typedef struct {}_s* {};\n", n, n));
    }
    for (id, s) in checked.structs.iter().enumerate() {
        cg.emit_struct_typedef(&mut out, id as u32, s);
    }
    if !checked.structs.is_empty() {
        out.push('\n');
    }

    for item in &file.items {
        if let Item::Func(f) = item {
            if f.name != "main" {
                cg.emit_func(&mut out, f);
            }
        }
    }
    for item in &file.items {
        if let Item::Func(f) = item {
            if f.name == "main" {
                cg.emit_main(&mut out, f);
            }
        }
    }
    out
}

struct Codegen<'a> {
    sigs: &'a SigTable,
    symbols: &'a HashMap<String, (u32, usize)>,
    enums: &'a [EnumInfo],
    structs: &'a [StructInfo],
}

impl<'a> Codegen<'a> {
    /// If `ty` is a tagged enum, its struct id; otherwise `None`.
    fn tagged_id(&self, ty: Ty) -> Option<u32> {
        match ty {
            Ty::Enum(id) if self.enums.get(id as usize).map_or(false, |e| e.tagged) => Some(id),
            _ => None,
        }
    }

    /// The C type for a Nullang type: a tagged-enum struct, a struct handle, or
    /// the scalar lowering otherwise (SPEC §7, §11).
    fn c_type_of(&self, ty: Ty) -> String {
        if let Ty::Struct(id) = ty {
            return struct_type_name(id);
        }
        match self.tagged_id(ty) {
            Some(id) => enum_struct_name(id),
            None => ty.c_type().to_string(),
        }
    }

    /// Emit a struct's C body: `struct nlstruct<id>_s { <fty> nlf_<name>; … };`.
    /// The handle typedef is forward-declared by `emit`, so field types may be
    /// other struct handles (pointers), including self-reference.
    fn emit_struct_typedef(&self, out: &mut String, id: u32, s: &StructInfo) {
        out.push_str(&format!("struct {}_s {{\n", struct_type_name(id)));
        for (name, fty) in &s.fields {
            out.push_str(&format!("  {} {};\n", self.c_type_of(*fty), mangle_field(name)));
        }
        out.push_str("};\n");
    }

    /// A zero-initialiser for a fresh temporary of this type. Tagged enums
    /// are structs and need `{0}`; scalars accept it too but read clearer as `0`.
    fn zero_of(&self, ty: Ty) -> &'static str {
        if self.tagged_id(ty).is_some() {
            "{0}"
        } else {
            "0"
        }
    }

    fn emit_enum_typedef(&self, out: &mut String, id: u32, e: &EnumInfo) {
        out.push_str("typedef struct {\n  long tag;\n  union {\n");
        for (idx, v) in e.variants.iter().enumerate() {
            if let Some(pty) = v.payload {
                out.push_str(&format!("    {} _v{};\n", pty.c_type(), idx));
            }
        }
        out.push_str(&format!("  }} u;\n}} {};\n\n", enum_struct_name(id)));
    }

    fn emit_func(&self, out: &mut String, f: &Func) {
        let ret = self.sigs.get(&f.name).map(|s| s.ret).unwrap_or(Ty::Unit);
        let mut locals: HashMap<String, Ty> = HashMap::new();
        let mut params = Vec::new();
        for (i, p) in f.params.iter().enumerate() {
            let ty = self
                .sigs
                .get(&f.name)
                .and_then(|s| s.params.get(i).copied())
                .unwrap_or(Ty::Int);
            locals.insert(p.name.clone(), ty);
            if ty != Ty::World {
                params.push(format!("{} {}", self.c_type_of(ty), mangle(&p.name)));
            }
        }
        let param_list = if params.is_empty() {
            "void".to_string()
        } else {
            params.join(", ")
        };
        let c_fn = self
            .sigs
            .get(&f.name)
            .map(|s| s.c_name.clone())
            .unwrap_or_else(|| mangle(&f.name));
        out.push_str(&format!("{} {}({}) {{\n", self.c_type_of(ret), c_fn, param_list));

        let mut fresh = 0usize;
        let tail = self.lower_block(&f.body, &locals, out, &mut fresh);
        match tail {
            Some(v) if ret != Ty::Unit && !v.is_empty() => {
                out.push_str(&format!("  return {};\n", v))
            }
            Some(v) if !v.is_empty() => out.push_str(&format!("  {};\n", v)),
            _ => {}
        }
        out.push_str("}\n\n");
    }

    fn emit_main(&self, out: &mut String, f: &Func) {
        let mut locals: HashMap<String, Ty> = HashMap::new();
        for p in &f.params {
            locals.insert(p.name.clone(), p.ty.resolved.unwrap_or(Ty::World));
        }
        // argv form so `argc`/`argv` builtins can reach the command line;
        // the globals are always assigned (cheap, no warning) even when unused.
        out.push_str("int main(int argc, char** argv) {\n");
        out.push_str("  nl_argc = argc; nl_argv = argv;\n");
        let mut fresh = 0usize;
        let tail = self.lower_block(&f.body, &locals, out, &mut fresh);
        match tail {
            Some(v) if !v.is_empty() => out.push_str(&format!("  return {};\n", v)),
            _ => out.push_str("  return 0;\n"),
        }
        out.push_str("}\n\n");
    }

    /// Emit a block's statements (child scope) and return its trailing value.
    fn lower_block(
        &self,
        block: &Block,
        outer: &HashMap<String, Ty>,
        out: &mut String,
        fresh: &mut usize,
    ) -> Option<String> {
        let mut locals = outer.clone();
        for stmt in &block.stmts {
            self.lower_stmt(stmt, &mut locals, out, fresh);
        }
        block.tail.as_ref().map(|e| self.lower(e, &locals, out, fresh))
    }

    /// Emit a block, assigning its trailing value to `target`.
    fn lower_block_into(
        &self,
        block: &Block,
        target: &str,
        outer: &HashMap<String, Ty>,
        out: &mut String,
        fresh: &mut usize,
    ) {
        let mut locals = outer.clone();
        for stmt in &block.stmts {
            self.lower_stmt(stmt, &mut locals, out, fresh);
        }
        if let Some(e) = &block.tail {
            let v = self.lower(e, &locals, out, fresh);
            if !v.is_empty() {
                out.push_str(&format!("  {} = {};\n", target, v));
            }
        }
    }

    /// Emit a block whose trailing value (if any) is used only for effect.
    fn lower_block_stmt(
        &self,
        block: &Block,
        outer: &HashMap<String, Ty>,
        out: &mut String,
        fresh: &mut usize,
    ) {
        let mut locals = outer.clone();
        for stmt in &block.stmts {
            self.lower_stmt(stmt, &mut locals, out, fresh);
        }
        if let Some(e) = &block.tail {
            let v = self.lower(e, &locals, out, fresh);
            if !v.is_empty() {
                out.push_str(&format!("  {};\n", v));
            }
        }
    }

    fn lower_stmt(
        &self,
        stmt: &Stmt,
        locals: &mut HashMap<String, Ty>,
        out: &mut String,
        fresh: &mut usize,
    ) {
        match stmt {
            Stmt::Let { name, ty: ann, value, .. } => {
                // Prefer the annotation when present: an empty `[]` cannot be
                // typed from its value. `List<scalar>` resolves in the parser;
                // `List<struct>` does not (no struct table there), so resolve it
                // here against the struct table. For everything else the
                // annotation equals the inferred type, so this is harmless.
                let ty = ann
                    .as_ref()
                    .and_then(|t| self.resolve_typeref(t))
                    .unwrap_or_else(|| self.ty_of(value, locals));
                let v = self.lower(value, locals, out, fresh);
                if !v.is_empty() {
                    out.push_str(&format!("  {} {} = {};\n", self.c_type_of(ty), mangle(name), v));
                }
                locals.insert(name.clone(), ty);
            }
            Stmt::Expr(e) => {
                let v = self.lower(e, locals, out, fresh);
                if !v.is_empty() {
                    out.push_str(&format!("  {};\n", v));
                }
            }
            Stmt::Return { value, .. } => match value {
                Some(e) => {
                    let v = self.lower(e, locals, out, fresh);
                    out.push_str(&format!("  return {};\n", v));
                }
                None => out.push_str("  return;\n"),
            },
            Stmt::Assign { name, value, .. } => {
                let v = self.lower(value, locals, out, fresh);
                if !v.is_empty() {
                    out.push_str(&format!("  {} = {};\n", mangle(name), v));
                }
            }
            Stmt::FieldAssign { target, value, .. } => {
                // `target` is a field chain; lowering it yields the C lvalue
                // (`(p)->nlf_x`). Reference semantics make the write visible
                // through every alias of the handle.
                let lhs = self.lower(target, locals, out, fresh);
                let v = self.lower(value, locals, out, fresh);
                out.push_str(&format!("  {} = {};\n", lhs, v));
            }
            Stmt::While { cond, body, .. } => {
                // `for(;;)` with the condition re-lowered inside the loop: the
                // cond may emit prelude statements (a lowered if/match), which
                // must run every iteration, not once before it.
                out.push_str("  for (;;) {\n");
                let c = self.lower(cond, locals, out, fresh);
                out.push_str(&format!("  if (!({})) break;\n", c));
                self.lower_block_stmt(body, locals, out, fresh);
                out.push_str("  }\n");
            }
        }
    }

    fn lower(
        &self,
        e: &Expr,
        locals: &HashMap<String, Ty>,
        out: &mut String,
        fresh: &mut usize,
    ) -> String {
        match e {
            Expr::Str { value, .. } => c_string_literal(value),
            Expr::Int { value, .. } => format!("{}", value),
            Expr::Bool { value, .. } => (if *value { "1" } else { "0" }).to_string(),
            Expr::Ident { name, .. } => mangle(name),
            Expr::Symbol { name, arg, .. } => {
                let (id, idx) = self.symbols.get(name).copied().unwrap_or((0, 0));
                // A payload-free enum is a bare index; a tagged enum (even a
                // bare variant of one) is a `{ tag, union }` compound literal.
                if self.tagged_id(Ty::Enum(id)).is_some() {
                    let sname = enum_struct_name(id);
                    match arg {
                        Some(e) => {
                            let v = self.lower(e, locals, out, fresh);
                            format!("(({}){{ .tag = {}, .u._v{} = {} }})", sname, idx, idx, v)
                        }
                        None => format!("(({}){{ .tag = {} }})", sname, idx),
                    }
                } else {
                    format!("{}", idx)
                }
            }
            Expr::Unary { operand, .. } => format!("(-{})", self.lower(operand, locals, out, fresh)),
            Expr::Binary { op, lhs, rhs, .. } => {
                let l = self.lower(lhs, locals, out, fresh);
                let r = self.lower(rhs, locals, out, fresh);
                // String equality compares contents, not pointers: lower to
                // `strcmp(l, r) == 0` / `!= 0`. The checker guarantees both
                // sides are String here.
                if op.is_equality() && self.ty_of(lhs, locals) == Ty::String {
                    format!("(strcmp({}, {}) {} 0)", l, r, op.c_op())
                } else {
                    format!("({} {} {})", l, op.c_op(), r)
                }
            }
            Expr::Call { callee, args, .. } => {
                // List intrinsics lower to the `nl_list_*` runtime. `push`/`set`
                // box their value into the uniform slot by the list's element
                // type; they return void and are used in statement position.
                match callee.as_str() {
                    "list_len" => {
                        let b = self.lower(&args[0], locals, out, fresh);
                        return format!("nl_list_len({})", b);
                    }
                    "push" => {
                        let elem = self.list_elem_of(&args[0], locals);
                        let b = self.lower(&args[0], locals, out, fresh);
                        let v = self.lower(&args[1], locals, out, fresh);
                        return format!("nl_list_push({}, {})", b, box_slot(&v, elem));
                    }
                    "set" => {
                        let elem = self.list_elem_of(&args[0], locals);
                        let b = self.lower(&args[0], locals, out, fresh);
                        let i = self.lower(&args[1], locals, out, fresh);
                        let v = self.lower(&args[2], locals, out, fresh);
                        return format!("nl_list_set({}, {}, {})", b, i, box_slot(&v, elem));
                    }
                    _ => {}
                }
                let sig = self.sigs.get(callee);
                let c_name = sig.map(|s| s.c_name.clone()).unwrap_or_else(|| mangle(callee));
                let mut emitted = Vec::new();
                for (i, arg) in args.iter().enumerate() {
                    let is_world = sig
                        .and_then(|s| s.params.get(i))
                        .map_or(false, |p| *p == Ty::World);
                    if !is_world {
                        emitted.push(self.lower(arg, locals, out, fresh));
                    }
                }
                format!("{}({})", c_name, emitted.join(", "))
            }
            Expr::If { cond, then_blk, else_blk, .. } => {
                let ty = self.ty_of(e, locals);
                let c = self.lower(cond, locals, out, fresh);
                if ty == Ty::Unit {
                    out.push_str(&format!("  if ({}) {{\n", c));
                    self.lower_block_stmt(then_blk, locals, out, fresh);
                    out.push_str("  } else {\n");
                    self.lower_block_stmt(else_blk, locals, out, fresh);
                    out.push_str("  }\n");
                    String::new()
                } else {
                    let tmp = self.fresh_var(fresh);
                    out.push_str(&format!("  {} {} = {};\n", self.c_type_of(ty), tmp, self.zero_of(ty)));
                    out.push_str(&format!("  if ({}) {{\n", c));
                    self.lower_block_into(then_blk, &tmp, locals, out, fresh);
                    out.push_str("  } else {\n");
                    self.lower_block_into(else_blk, &tmp, locals, out, fresh);
                    out.push_str("  }\n");
                    tmp
                }
            }
            Expr::Match { scrutinee, arms, .. } => {
                let ty = self.ty_of(e, locals);
                let scrut_ty = self.ty_of(scrutinee, locals);
                let scrut = self.lower(scrutinee, locals, out, fresh);
                let tmp = if ty == Ty::Unit {
                    None
                } else {
                    let t = self.fresh_var(fresh);
                    out.push_str(&format!("  {} {} = {};\n", self.c_type_of(ty), t, self.zero_of(ty)));
                    Some(t)
                };
                // A tagged enum is matched on its `.tag`; bind the scrutinee to
                // a temporary so payloads can be read out. A payload-free enum
                // switches on its bare value directly.
                let (switch_on, scrut_var) = match self.tagged_id(scrut_ty) {
                    Some(id) => {
                        let sv = self.fresh_var(fresh);
                        out.push_str(&format!("  {} {} = {};\n", enum_struct_name(id), sv, scrut));
                        (format!("{}.tag", sv), Some(sv))
                    }
                    None => (scrut, None),
                };
                out.push_str(&format!("  switch ({}) {{\n", switch_on));
                for arm in arms {
                    let (id, idx) = self.symbols.get(&arm.symbol).copied().unwrap_or((0, 0));
                    out.push_str(&format!("  case {}: {{\n", idx));
                    let mut arm_locals = locals.clone();
                    // Bind the payload into the arm scope, unless discarded (`_`).
                    if let (Some(sv), Some(binder)) = (&scrut_var, &arm.binder) {
                        if binder != "_" {
                            if let Some(pty) = self.enums[id as usize].variants[idx].payload {
                                out.push_str(&format!(
                                    "  {} {} = {}.u._v{};\n",
                                    self.c_type_of(pty),
                                    mangle(binder),
                                    sv,
                                    idx
                                ));
                                arm_locals.insert(binder.clone(), pty);
                            }
                        }
                    }
                    let v = self.lower(&arm.body, &arm_locals, out, fresh);
                    match &tmp {
                        Some(t) if !v.is_empty() => out.push_str(&format!("  {} = {};\n", t, v)),
                        _ if !v.is_empty() => out.push_str(&format!("  {};\n", v)),
                        _ => {}
                    }
                    out.push_str("  break;\n  }\n");
                }
                out.push_str("  default: break;\n  }\n");
                tmp.unwrap_or_default()
            }
            Expr::ListLit { elems, .. } => {
                // Build a fresh handle and push each element (boxed by its own
                // type). An empty `[]` just yields a new empty list.
                let tmp = self.fresh_var(fresh);
                out.push_str(&format!("  nl_list {} = nl_list_new();\n", tmp));
                for e in elems {
                    let ety = self.ty_of(e, locals);
                    let v = self.lower(e, locals, out, fresh);
                    let elem = ElemTy::from_ty(ety).unwrap_or(ElemTy::Int);
                    out.push_str(&format!("  nl_list_push({}, {});\n", tmp, box_slot(&v, elem)));
                }
                tmp
            }
            Expr::Index { base, index, .. } => {
                let elem = self.list_elem_of(base, locals);
                let b = self.lower(base, locals, out, fresh);
                let i = self.lower(index, locals, out, fresh);
                unbox_slot(&format!("nl_list_get({}, {})", b, i), elem)
            }
            Expr::StructLit { name, fields, .. } => {
                // Allocate the handle, then assign each field. Field values are
                // lowered in declaration order of the literal (effects, if any,
                // already ran by the time the handle is returned).
                let id = self.struct_id(name).unwrap_or(0);
                let tname = struct_type_name(id);
                let tmp = self.fresh_var(fresh);
                out.push_str(&format!(
                    "  {} {} = malloc(sizeof(*{}));\n",
                    tname, tmp, tmp
                ));
                for fi in fields {
                    let v = self.lower(&fi.value, locals, out, fresh);
                    out.push_str(&format!("  {}->{} = {};\n", tmp, mangle_field(&fi.name), v));
                }
                tmp
            }
            Expr::Field { base, field, .. } => {
                let b = self.lower(base, locals, out, fresh);
                format!("({})->{}", b, mangle_field(field))
            }
        }
    }

    /// The struct table id for a struct name (linear scan; tables are tiny).
    fn struct_id(&self, name: &str) -> Option<u32> {
        self.structs.iter().position(|s| s.name == name).map(|i| i as u32)
    }

    /// Resolve a written `TypeRef` to a `Ty` against the struct table — the
    /// codegen mirror of the checker's resolver, needed for `List<struct>`
    /// annotations the parser leaves unresolved (it has no struct table).
    fn resolve_typeref(&self, t: &TypeRef) -> Option<Ty> {
        if let Some(ty) = t.resolved {
            return Some(ty);
        }
        if let Some(elem) = &t.elem {
            return self.resolve_typeref(elem).and_then(ElemTy::from_ty).map(Ty::List);
        }
        self.struct_id(&t.name).map(Ty::Struct)
    }

    /// The element type of a list-typed expression (best effort; the checker
    /// proved it is a List). Defaults to Int so codegen never panics.
    fn list_elem_of(&self, e: &Expr, locals: &HashMap<String, Ty>) -> ElemTy {
        match self.ty_of(e, locals) {
            Ty::List(elem) => elem,
            _ => ElemTy::Int,
        }
    }

    fn fresh_var(&self, fresh: &mut usize) -> String {
        let v = format!("_t{}", *fresh);
        *fresh += 1;
        v
    }

    /// Best-effort C type of an expression (the checker proved soundness).
    fn ty_of(&self, e: &Expr, locals: &HashMap<String, Ty>) -> Ty {
        match e {
            Expr::Str { .. } => Ty::String,
            Expr::Int { .. } => Ty::Int,
            Expr::Bool { .. } => Ty::Bool,
            Expr::Symbol { name, .. } => self
                .symbols
                .get(name)
                .map(|(id, _)| Ty::Enum(*id))
                .unwrap_or(Ty::Int),
            Expr::Ident { name, .. } => locals.get(name).copied().unwrap_or(Ty::Int),
            Expr::Unary { .. } => Ty::Int,
            Expr::Binary { op, .. } => {
                if op.is_arithmetic() {
                    Ty::Int
                } else {
                    Ty::Bool
                }
            }
            Expr::Call { callee, .. } => {
                // `list_len` is a polymorphic intrinsic, not in the SigTable.
                if callee == "list_len" {
                    Ty::Int
                } else {
                    self.sigs.get(callee).map(|s| s.ret).unwrap_or(Ty::Unit)
                }
            }
            Expr::ListLit { elems, .. } => match elems.first() {
                Some(e) => ElemTy::from_ty(self.ty_of(e, locals))
                    .map(Ty::List)
                    .unwrap_or(Ty::List(ElemTy::Int)),
                None => Ty::List(ElemTy::Int), // empty; real type comes from annotation
            },
            Expr::Index { base, .. } => match self.ty_of(base, locals) {
                Ty::List(elem) => elem.as_ty(),
                _ => Ty::Int,
            },
            Expr::StructLit { name, .. } => {
                self.struct_id(name).map(Ty::Struct).unwrap_or(Ty::Int)
            }
            Expr::Field { base, field, .. } => match self.ty_of(base, locals) {
                Ty::Struct(id) => self
                    .structs
                    .get(id as usize)
                    .and_then(|s| s.fields.iter().find(|(n, _)| n == field))
                    .map(|(_, t)| *t)
                    .unwrap_or(Ty::Int),
                _ => Ty::Int,
            },
            Expr::If { then_blk, .. } => match &then_blk.tail {
                Some(t) => self.ty_of(t, locals),
                None => Ty::Unit,
            },
            Expr::Match { arms, .. } => match arms.first() {
                Some(a) => {
                    // The result type is the arm body's type; bind the first
                    // arm's payload so a body that returns it types correctly.
                    let mut l = locals.clone();
                    if let Some(b) = &a.binder {
                        if b != "_" {
                            if let Some((id, idx)) = self.symbols.get(&a.symbol).copied() {
                                if let Some(pty) = self.enums[id as usize].variants[idx].payload {
                                    l.insert(b.clone(), pty);
                                }
                            }
                        }
                    }
                    self.ty_of(&a.body, &l)
                }
                None => Ty::Unit,
            },
        }
    }
}

/// Mangle a user identifier for C. A Nullang name like `double`, `int`,
/// `return` is a C keyword and would not compile; prefixing dodges every C
/// keyword *and* our runtime symbols (`nullang_*`, `nl_argc`/`nl_argv`,
/// `nlenum*`, `_t*` — none start with `nlu_`). `main` is the C entry point and
/// stays verbatim (it is never referenced as a value, so no call site relies on
/// the prefix). The map is injective, so distinct names stay distinct.
pub fn mangle(name: &str) -> String {
    if name == "main" {
        "main".to_string()
    } else {
        format!("nlu_{}", name)
    }
}

/// Box a lowered value into a list's uniform 64-bit slot. A String or struct is
/// stored as its pointer (via `intptr_t`, safe on LP64); Int/Bool fit a `long`.
fn box_slot(v: &str, elem: ElemTy) -> String {
    match elem {
        ElemTy::String | ElemTy::Struct(_) => format!("(long)(intptr_t)({})", v),
        _ => format!("(long)({})", v),
    }
}

/// Unbox a slot read back into the element's C type — the inverse of `box_slot`.
fn unbox_slot(v: &str, elem: ElemTy) -> String {
    match elem {
        ElemTy::String => format!("(const char*)(intptr_t)({})", v),
        ElemTy::Struct(id) => format!("({})(intptr_t)({})", struct_type_name(id), v),
        ElemTy::Bool => format!("(int)({})", v),
        ElemTy::Int => format!("(long)({})", v),
    }
}

/// Re-escape a decoded string into a C string literal.
fn c_string_literal(s: &str) -> String {
    let mut out = String::from("\"");
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
